### ISSUE TITLE
Please add support for delimiter "pipe" which looks like "|"  Also: colon and semicolon.

### ISSUE THREAD

**Issue by rynes** [Clever/csvlint#2]
The pipe delimiter "|" is very popular and is the default for applications like sqlite which I use. Please add the pipe to csvlint as a delimiter. Also, next in line are probably colon (":") and then semicolon (";"). Adding them when you are in there might save time in the future. Since I don't have a go compiler, please update the windows executable "csvlint.exe".

**Comment by schimmy** [comment]
Hey @rynes, we've added support with https://github.com/Clever/csvlint/pull/5, released as https://github.com/Clever/csvlint/releases/tag/v0.2.0. Please let me know how the change is working for you, and thanks for using csvlint!
