### ISSUE TITLE
Make the help information syntax obtained at the command line match that in the readme.md file

### ISSUE THREAD

**Issue by rynes** [Clever/csvlint#3]
The readme.md file has these examples:

    $ csvlint bad_quote.csv
    $ csvlint --lazyquotes bad_quote.csv
    $ csvlint mult_long_columns.csv
    $ csvlint --delimiter=tab mult_long_columns_tabs.csv
    $ csvlint one_long_column.csv
    $ csvlint perfect.csv

whereas the command line help shows this:

    Usage of csvlint:
      -delimiter="comma": field delimiter in the file. options: comma, tab
      -help=false: print help and exit
      -lazyquotes=false: try to parse improperly escaped quotes

**Comment by schimmy** [comment]
this should be fixed with the latest release, since I had to change the command line arguments anyway: https://github.com/Clever/csvlint/releases/tag/v0.2.0
Thanks for the help!

**Comment by rynes** [comment]
Maybe I’m doing something wrong, but it seems to say everything is valid. I took a small csv file using commas and changed them to pipe and it said valid. I changed one of the pipes on the header line to ^ and it said valid. I changed the delimiter value to ”w” and it said valid.

**Comment by azylman** [comment]
@rynes: without seeing the files I'm not certain, but those all sound valid.

For instance, this is a valid CSV file with a delimiter of either `,` or `|`:

```
header1|header2|header3
val1|val2|val3
```

When the delimiter is a `|`, this is a file with three columns, where the first row looks like `["header1", "header2", "header3"]`.

When the delimiter is a `,`, this is a file with one column, where the first row looks like `["header1|header2|header3"]`.
